/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WishListRouteImport } from './routes/WishListRoute'
import { Route as StatisticsRouteImport } from './routes/StatisticsRoute'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WishListRouteRoute = WishListRouteImport.update({
  id: '/WishListRoute',
  path: '/WishListRoute',
  getParentRoute: () => rootRoute,
} as any)

const StatisticsRouteRoute = StatisticsRouteImport.update({
  id: '/StatisticsRoute',
  path: '/StatisticsRoute',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/StatisticsRoute': {
      id: '/StatisticsRoute'
      path: '/StatisticsRoute'
      fullPath: '/StatisticsRoute'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRoute
    }
    '/WishListRoute': {
      id: '/WishListRoute'
      path: '/WishListRoute'
      fullPath: '/WishListRoute'
      preLoaderRoute: typeof WishListRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/StatisticsRoute': typeof StatisticsRouteRoute
  '/WishListRoute': typeof WishListRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/StatisticsRoute': typeof StatisticsRouteRoute
  '/WishListRoute': typeof WishListRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/StatisticsRoute': typeof StatisticsRouteRoute
  '/WishListRoute': typeof WishListRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/StatisticsRoute' | '/WishListRoute'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/StatisticsRoute' | '/WishListRoute'
  id: '__root__' | '/' | '/StatisticsRoute' | '/WishListRoute'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatisticsRouteRoute: typeof StatisticsRouteRoute
  WishListRouteRoute: typeof WishListRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatisticsRouteRoute: StatisticsRouteRoute,
  WishListRouteRoute: WishListRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/StatisticsRoute",
        "/WishListRoute"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/StatisticsRoute": {
      "filePath": "StatisticsRoute.tsx"
    },
    "/WishListRoute": {
      "filePath": "WishListRoute.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
